#!/bin/bash

if [[ $DOCKER_TAG == v2* ]]; then
    echo "docker tag $IMAGE_NAME $DOCKER_REPO:v2"
    echo "docker push $DOCKER_REPO:v2"
fi

if [[ $DOCKER_TAG == v3* ]]; then
    echo "docker tag $IMAGE_NAME $DOCKER_REPO:v3"
    echo "docker tag $IMAGE_NAME $DOCKER_REPO:latest"
    echo "docker push $DOCKER_REPO:v3"
    echo "docker push $DOCKER_REPO:latest"
fi
